### ISSUE TITLE
Setting batch modulations to zero

### ISSUE THREAD

**Issue by bkoyuncu** [deepmind/functa#10]
Hi,

Thanks for making the code available! I was not able to find the implementation of _set batch modulations to zero_  (it is defined in 4th line of Algorithm 1 in the paper) in the repo. Would you mind pointing that part to us?

Thank in advance,
Best regards

**Comment by hyunjik11** [comment]
Hi, this is done by setting `latent_init_scale=0.` in `experiment_meta_learning.py`. I've just made the change and pushed to the repo, so you should be able to see this change in the file. I hope that helps.

**Comment by bkoyuncu** [comment]
Hi thanks so much, does this initialization also guarantee that modulations are zerod after every outer loop training?

**Comment by hyunjik11** [comment]
Yes. Setting this to 0 ensures that the latent [`modulations`](https://github.com/deepmind/functa/blob/main/function_reps.py#L294-L297) that are part of the `self._params` are initialized to 0 inside the [`__init__`](https://github.com/deepmind/functa/blob/main/experiment_meta_learning.py#L186-L188) of experiment_meta_learning.py.
These initial values are fixed throughout the meta-learning training since the `_update_func` only updates the `weights` and keeps the `modulations` fixed (see [here](https://github.com/deepmind/functa/blob/main/experiment_meta_learning.py#L372-L378)).
