### ISSUE TITLE
3DShapeNet 데이터를 이용하는 모델 관련 코드를 제공해주실 수 있으신 지 궁금합니다!

### ISSUE THREAD

**Issue by joohyukparkkk** [deepmind/functa#2]
안녕하세요

저는 포항공과대학교 전자전기공학과 학부생입니다.

다름이 아니라, 해당 논문에서 3DShapeNet 데이터를 이용하여 얻은 결과 이미지를 확인할 수 있었습니다.
제가 지금 하고 있는 연구가 이처럼 3D Generation, Reocnstruction 관련된 연구라 3DShapeNet 데이터를 입력으로 받는 메타 러닝 기반 모델의 코드가 github에 제공된다면 좋을 것 같다고 생각했습니다. 아직 해당 github 페이지에는 3DShapeNet 데이터를 활용하여 modulation vector(INR 일부)를 얻는 코드는 제공되어 있지 않은 것 같습니다.

혹시 이와 관련된 코드를 제공해주실 수 있으신지 궁금합니다!

감사합니다.

**Comment by joohyukparkkk** [comment]
추가로, NSF, DDPM 등의 생성 모델 코드도 제공해주실 수 있는지 궁금합니다!

**Comment by hyunjik11** [comment]
Hi Joonhyuk, I did look into this at the time the paper was published, but unfortunately we did not receive permission from DM to open source the code related to the 3D shapenet data due to licensing issues of the 3D Shapenet dataset, restricting the use of the dataset to educational and non-commercial research. Apologies for the inconvenience and I hope you understand. However you should be able to reproduce the results in the paper in a straightforward manner from the comprehensive details in the appendix of the paper and using the public 3D shapenet data here: http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1.binvox.zip (you'll need to sign up and get your registration approved first).
