### ISSUE TITLE
experiment-meta-learning.py --config=None error

### ISSUE THREAD

**Issue by seoyunYang** [deepmind/functa#3]
hi.
test_celeb_a_hq works fine but when running experiment-meta-learning, 
if __name__ == '__main__':
  flags.mark_flag_as_required('config')
  app.run(functools.partial(platform.main, Experiment))

flags.mark_flag_as_required('config') returns the following error: FATAL Flags parsing error: flag --config=None: Flag --config must have a value other than None.
i was wondering why this problem is happening

**Comment by iacopo97** [comment]
Hi, I have found a solution that works for me. the following part is needed at the end of the code instead of platform.main.
if name == 'main':
flags.mark_flag_as_required('config')
app.run(functools.partial(platform.main, Experiment))
Then I included the following python modules:
from absl import app
import functools

At the end  I introduce inside the function get config():
´´´
config.checkpoint_dir = '/tmp/training/' #this is my checkpoint_directory, I have specified this directory also for config.eval_specific_checkpoint_dir 

Then in order to execute the experiment_meta_learning.py i use the following line in the terminal:
python3 ./experiment_meta_learning.py --config ./experiment_meta_learning.py
